spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/demo
          jwk-set-uri: http://localhost:8083/auth/realms/demo/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: demo
    password: demo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${SMTP_MAIL_HOST}
    port: ${SMTP_MAIL_PORT}
    username: ${SMTP_MAIL_USERNAME}
    password: ${SMTP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
